config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  get 'my_list', to: 'pages#my_list', as: 'my_list'
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }, sign_out_via: [:get, :delete]

  resources :resumes, except: [:index] do
    member do
      patch :toggle_active
    end
  end
  
  resources :vacancies, except: [:index] do
    member do
      patch :toggle_active
    end
  end
end

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/index.html.erb
<div class="container mt-4">
  <% if current_user.worker? %>
    <section class="mb-5">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h2>Доступные вакансии</h2>
        <div class="col-md-4">
          <%= form_tag root_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :search, params[:search], class: "form-control me-2", placeholder: "Искать вакансии..." %>
            <%= submit_tag "Поиск", class: "btn btn-outline-primary" %>
          <% end %>
        </div>
      </div>
      <div class="row justify-content-center">
        <% if @vacancies.any? %>
          <% @vacancies.each do |vacancy| %>
            <div class="col-sm-10 col-md-6 col-lg-6 mb-4">
              <%= link_to vacancy_path(vacancy), class: "text-decoration-none" do %>
                <div class="card border-primary shadow-sm h-100 hover-shadow" style="min-height: 300px;">
                  <div class="card-body d-flex flex-column">
                    <div class="d-flex justify-content-between align-items-start mb-2">
                      <h5 class="card-title text-primary"><%= vacancy.title %></h5>
                      <small class="text-muted"><%= time_ago_in_words(vacancy.created_at) %> назад</small>
                    </div>
                    <p class="card-text flex-grow-1 text-dark"><%= truncate(vacancy.description, length: 100) %></p>
                    <ul class="list-unstyled mb-4 text-dark">
                      <li><strong>Требуемые навыки:</strong> <%= truncate(vacancy.skills_required, length: 50) %></li>
                      <li><strong>Заработная плата:</strong> <%= format_currency(vacancy.salary_min, vacancy.currency) %> - <%= format_currency(vacancy.salary_max, vacancy.currency) %></li>
                    </ul>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <p class="text-center text-muted">На данный момент вакансий нет.</p>
        <% end %>
      </div>
      <div class="d-flex justify-content-center mt-4">
        <%= paginate @vacancies if @vacancies %>
      </div>
    </section>
  <% elsif current_user.employer? %>
    <section class="mb-5">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h2>Доступные резюме</h2>
        <div class="col-md-4">
          <%= form_tag root_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :search, params[:search], class: "form-control me-2", placeholder: "Искать резюме..." %>
            <%= submit_tag "Поиск", class: "btn btn-outline-primary" %>
          <% end %>
        </div>
      </div>
      <div class="row justify-content-center">
        <% if @resumes.any? %>
          <% @resumes.each do |resume| %>
            <div class="col-sm-10 col-md-6 col-lg-6 mb-4">
              <%= link_to resume_path(resume), class: "text-decoration-none" do %>
                <div class="card border-primary shadow-sm h-100 hover-shadow" style="min-height: 300px;">
                  <div class="card-body d-flex flex-column">
                    <div class="d-flex justify-content-between align-items-start mb-2">
                      <h5 class="card-title text-primary"><%= resume.title %></h5>
                      <small class="text-muted"><%= time_ago_in_words(resume.created_at) %> назад</small>
                    </div>
                    <p class="card-text flex-grow-1 text-dark"><%= truncate(resume.description, length: 100) %></p>
                    <ul class="list-unstyled mb-4 text-dark">
                      <li><strong>Навыки:</strong> <%= truncate(resume.skills, length: 50) %></li>
                      <li><strong>Ожидаемая зарплата:</strong> <%= format_currency(resume.salary_expectation, resume.currency) %></li>
                    </ul>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <p class="text-center text-muted">На данный момент резюме нет.</p>
        <% end %>
      </div>
      <div class="d-flex justify-content-center mt-4">
        <%= paginate @resumes if @resumes %>
      </div>
    </section>
  <% end %>
</div>

<% content_for :styles do %>
  <style>
      .hover-shadow {
          transition: box-shadow 0.3s ease-in-out;
      }
      .hover-shadow:hover {
          box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15) !important;
          cursor: pointer;
      }
  </style>
<% end %>

app/views/pages/my_list.html.erb
<div class="container mt-4">
  <% if current_user.worker? %>
    <section class="mb-5">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="mb-4">Мои резюме</h2>
        <%= link_to "Создать новое резюме", new_resume_path, class: "btn btn-success" %>
      </div>
      <div class="row justify-content-center">
        <% if @resumes.any? %>
          <% @resumes.each do |resume| %>
            <div class="col-sm-10 col-md-6 col-lg-6 mb-4">
              <%= link_to resume_path(resume), class: "text-decoration-none" do %>
                <div class="card border-primary shadow-sm h-100 hover-shadow">
                  <div class="card-body d-flex flex-column">
                    <div class="d-flex justify-content-between align-items-start mb-2">
                      <h5 class="card-title text-primary"><%= resume.title %></h5>
                      <div class="d-flex align-items-center">
                        <small class="text-muted me-2"><%= time_ago_in_words(resume.created_at) %> ago</small>
                        <span class="badge <%= resume.is_active ? 'bg-success' : 'bg-secondary' %> rounded-pill">
                          <%= resume.is_active ? 'Активно' : 'Не активно' %>
                        </span>
                      </div>
                    </div>
                    <p class="card-text flex-grow-1 text-dark"><%= truncate(resume.description, length: 100) %></p>
                    <ul class="list-unstyled mb-0 text-dark">
                      <li><strong>Навыки:</strong> <%= truncate(resume.skills, length: 50) %></li>
                      <li><strong>Ожидаемая зарплата:</strong> <%= format_currency(resume.salary_expectation, resume.currency) %></li>
                    </ul>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <p class="text-center text-muted">У вас еще нет резюме. Для начала, создайте его!</p>
        <% end %>
      </div>
    </section>
  <% elsif current_user.employer? %>
    <section class="mb-5">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="mb-4">Мои Вакансии</h2>
        <%= link_to "Создать вакансию", new_vacancy_path, class: "btn btn-success" %>
      </div>
      <div class="row justify-content-center">
        <% if @vacancies.any? %>
          <% @vacancies.each do |vacancy| %>
            <div class="col-sm-11 col-md-7 col-lg-6 mb-4">
              <%= link_to vacancy_path(vacancy), class: "text-decoration-none" do %>
                <div class="card border-primary shadow-sm h-100 hover-shadow">
                  <div class="card-body d-flex flex-column">
                    <div class="d-flex justify-content-between align-items-start mb-2">
                      <h5 class="card-title text-primary"><%= vacancy.title %></h5>
                      <div class="d-flex align-items-center">
                        <small class="text-muted me-2"><%= time_ago_in_words(vacancy.created_at) %> ago</small>
                        <span class="badge <%= vacancy.is_active ? 'bg-success' : 'bg-secondary' %> rounded-pill">
                          <%= vacancy.is_active ? 'Active' : 'Inactive' %>
                        </span>
                      </div>
                    </div>
                    <p class="card-text flex-grow-1 text-dark"><%= truncate(vacancy.description, length: 100) %></p>
                    <ul class="list-unstyled mb-0 text-dark">
                      <li><strong>Необходимые навыки:</strong> <%= truncate(vacancy.skills_required, length: 50) %></li>
                      <li><strong>Заработная плата:</strong> <%= format_currency(vacancy.salary_min, vacancy.currency) %> - <%= format_currency(vacancy.salary_max, vacancy.currency) %></li>
                    </ul>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <p class="text-center text-muted">У вас еще нет вакансий. Для начала, создайте её!</p>
        <% end %>
      </div>
    </section>
  <% end %>
  <div class="d-flex justify-content-center mt-4">
    <nav aria-label="Навигация по страницам">
      <ul class="pagination">
        <% if @vacancies&.any? || @resumes&.any? %>
          <% if @vacancies %>
            <%= paginate @vacancies, window: 2 do |page| %>
              <% if page.first? %>
                <li class="page-item <%= 'disabled' if page.current? %>">
                  <%= link_to_unless page.current?, "Первая", url_for(page: 1), class: "page-link" %>
                </li>
              <% elsif page.last? %>
                <li class="page-item <%= 'disabled' if page.current? %>">
                  <%= link_to_unless page.current?, "Последняя", url_for(page: page.number), class: "page-link" %>
                </li>
              <% else %>
                <li class="page-item <%= 'active' if page.current? %>">
                  <%= link_to_unless page.current?, page.number, url_for(page: page.number), class: "page-link" %>
                </li>
              <% end %>
            <% end %>
          <% elsif @resumes %>
            <%= paginate @resumes, window: 2 do |page| %>
              <% if page.first? %>
                <li class="page-item <%= 'disabled' if page.current? %>">
                  <%= link_to_unless page.current?, "Первая", url_for(page: 1), class: "page-link" %>
                </li>
              <% elsif page.last? %>
                <li class="page-item <%= 'disabled' if page.current? %>">
                  <%= link_to_unless page.current?, "Последняя", url_for(page: page.number), class: "page-link" %>
                </li>
              <% else %>
                <li class="page-item <%= 'active' if page.current? %>">
                  <%= link_to_unless page.current?, page.number, url_for(page: page.number), class: "page-link" %>
                </li>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </nav>
  </div>
</div>